NUM_CLASSES: 10
config:
  dropout_default: 0.5
  kernel_1: 16
  kernel_2: 16
  kernel_default: 16
  layer_fn_size_1: 200
  layer_fn_size_default: 100
  layer_size_1: 128
  layer_size_2: 200
  layer_size_default: 256
  loss_type: 1
  lr: 9.827371894065243e-05
  max_pool_1: 2
  max_pool_default: 2
  nbr_layer_cnn: 4
  nbr_layer_lin: 1
  stride_default: 1
input_shape: !!python/tuple
- 512
- 1
- 1024
