NUM_CLASSES: 8
config:
  dropout_default: 0.5
  gamma_neg: 0
  gamma_pos: 0
  kernel_1: 20
  kernel_2: 16
  kernel_default: 16
  layer_fn_size_1: 200
  layer_fn_size_default: 100
  layer_size_1: 200
  layer_size_2: 256
  layer_size_default: 256
  loss_clip: 0
  lr: 3.484904700622946e-05
  max_pool_1: 2
  max_pool_default: 2
  nbr_layer_cnn: 4
  nbr_layer_lin: 2
  stride_default: 1
input_shape: !!python/tuple
- 512
- 1
- 1024
